# Generate the kics2-runtime.cabal and install the package

# Name of the package
RUNTIME_PACKAGE = kics2-runtime
# Name of the cabal file
RUNTIME_CABAL = $(RUNTIMEDIR)/$(RUNTIME_PACKAGE).cabal
# Name of the cabal template
RUNTIME_CABAL_IN = $(RUNTIME_CABAL).in
# IDSupply implementation to use (see kics2-runtime.cabal for a list)
export RUNTIME_IDSUPPLY = idsupplyinteger

export RUNTIME = $(RUNTIME_CABAL)
export RUNTIME_ARTIFACTS = $(RUNTIMEDIR)/dist \
                           $(RUNTIMEDIR)/dist-newstyle \
                           $(RUNTIMEDIR)/.stack-work \
                           $(RUNTIMEDIR)/**/*.hi \
                           $(RUNTIMEDIR)/**/*.hi-boot \
                           $(RUNTIMEDIR)/**/*.o \
                           $(RUNTIMEDIR)/**/*.o-boot

$(RUNTIME_CABAL): $(RUNTIME_CABAL_IN) $(INSTALLHS) $(PACKAGEJSON)
	@envsubst < $< | sed "s/\(cabal-version:.*\)/\1\n\n-- NOTE: This file is autogenerated, please edit kics2-runtime.cabal.in!/g" > $@
